name: Update README

on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          # Required: GitHub Token with write access to the repository
          # Create a Personal Access Token with expiry < 366 days
          # with the `repo` scope and add it as a secret to your repository.
          GITHUB_TOKEN: ${{ secrets.HOMEPAGE_ACTION_TOKEN }}
        with:
          template: "templates/github-profile.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          # Go to the repository's Settings > Actions > General.
          # Scroll to the Workflow permissions section.
          # Ensure Read and write permissions is selected.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
